### ISSUE TITLE
Thumbnails listing images

### ISSUE THREAD

**Issue by rmaree** [cytomine/Cytomine-core-legacy#1042]
Thumbnails ne s'affichent pas, p.ex.
http://beta.cytomine.be/#tabs-images-126664109
http://beta.cytomine.be/#tabs-images-21907448

Mais certains autres projets OK:
http://beta.cytomine.be/#tabs-images-126702338

URL de l'image:
http://beta.cytomine.be/api/abstractimage/126678993/associated/macro.png?maxWidth=256
Error 500: 
Servlet: 
URI: 
Exception Message: Server returned HTTP response code: 500 for URL: http://image.cytomine.be/api/abstractimage/126678993/associated/macro?cytomineUrl=http://beta.cytomine.be&maxWidth=256 
Caused by: Server returned HTTP response code: 500 for URL: http://image.cytomine.be/api/abstractimage/126678993/associated/macro?cytomineUrl=http://beta.cytomine.be&maxWidth=256 
Class: APIAuthentificationFilters 
At Line: [21] 

Stack Trace

java.io.IOException: Server returned HTTP response code: 500 for URL: http://image.cytomine.be/api/abstractimage/126678993/associated/macro?cytomineUrl=http://beta.cytomine.be&maxWidth=256

```
at be.cytomine.image.AbstractImageService.getAssociatedImage(AbstractImageService.groovy:249)

at GrailsMelodyGrailsPlugin$_closure4_closure16_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:184)

at be.cytomine.api.image.RestAbstractImageController.label(RestAbstractImageController.groovy:210)

at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:195)

at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)

at net.bull.javamelody.JspWrapper.invoke(JspWrapper.java:151)

at net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:282)

at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:203)
```

http://image.cytomine.be/api/abstractimage/126678993/associated/macro?cytomineUrl=http://beta.cytomine.be&maxWidth=256 
Error 500: Internal Server Error
URI
/api/abstractimage/126678993/associated/macro
Class
java.lang.NoClassDefFoundError
Message
Could not initialize class org.openslide.OpenSlide

**Comment by stevben** [comment]
Bug parce l'Openslide.jar fournit avec le WAR a été compilé sous OS X et il ne trouve pas la JNI Lib openslide. Lors du prochain déploiement, ce problème disparaîtra car la lib Openslide deviendra OS agnostic. Il faudra alors spécifier le LD_LIBRARY_PATH où se trouve la lib système openslide pour régler le problème.

**Comment by stevben** [comment]
Pour régler le souci manuellement, une fois déployé, il suffit de remplacer openslide.jar par celui compilé localement sur le serveur de production 

```
cd /var/lib/tomcat7/webapps/ROOT/WEB-INF/lib
sudo cp /usr/local/lib/openslide-java/openslide.jar .
export LD_LIBRARY_PATH=/usr/local/lib/openslide-java/:$LD_LIBRARY_PATH
sudo /etc/init.d/tomcat7 restart
```
