### ISSUE TITLE
Share comment on job annotation generates an error

### ISSUE THREAD

**Issue by rmaree** [cytomine/Cytomine-core-legacy#1099]
When sharing a comment on a *Job* annotations from Cytomine-WebUI, the comment is not sent and we got an error, see below. Comment on a regular user's annotation is working nicely.

Request URL:http://demo.cytomine.be/api/annotation/17062035/comment.json
Request Method:POST
Status Code:500 Internal Server Error

Grails Runtime Exception

Error Details

Error 500: 
Servlet: 
URI: 
Exception Message: Cannot invoke method toCropURL() on null object 
Caused by: Cannot invoke method toCropURL() on null object 
Class: APIAuthentificationFilters 
At Line: [45] 
Code Snippet:
Stack Trace

java.lang.NullPointerException: Cannot invoke method toCropURL() on null object

	at be.cytomine.api.ontology.RestUserAnnotationController.addComment(RestUserAnnotationController.groovy:132)

	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)

	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)

	at net.bull.javamelody.JspWrapper.invoke(JspWrapper.java:151)

	at net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:282)

	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:203)

	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:181)

	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)

	at cytomine.web.APIAuthentificationFilters.doFilter(APIAuthentificationFilters.groovy:45)

	at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)

	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

	at java.lang.Thread.run(Thread.java:745)

**Comment by geektortoise** [comment]
https://github.com/cytomine/Cytomine-core/blob/9dec970072dd777b72cc0f0858e5ba40b649fb82/grails-app/domain/be/cytomine/ontology/SharedAnnotation.groovy#L40

**Comment by geektortoise** [comment]
Fixed by 2da6ec97f6fcb6e9c768186162b685eb6ccd126a
