### ISSUE TITLE
An error occurred while fetching annotations

### ISSUE THREAD

**Issue by pirottemarie** [cytomine/Cytomine-core-legacy#1194]
Hello,

An error message occured on the Cytomine viewer : "An error occurred while fetching annotations"

```
Grails Runtime Exception
Error Details
Error 500:
Servlet:
URI:
Exception Message: Cannot cast object 'null' with class 'null' to class 'int'. Try 'java.lang.Integer' instead
Caused by: Cannot cast object 'null' with class 'null' to class 'int'. Try 'java.lang.Integer' instead
Class: APIAuthentificationFilters
At Line: [46]
Code Snippet:
Stack Trace
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'null' with class 'null' to class 'int'. Try 'java.lang.Integer' instead

	at be.cytomine.utils.geometry.KmeansGeometryService.mustBeReduce(KmeansGeometryService.groovy:121)

	at be.cytomine.utils.geometry.KmeansGeometryService.mustBeReduce(KmeansGeometryService.groovy:95)

	at GrailsMelodyGrailsPlugin$_closure4_closure16_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:184)

	at be.cytomine.ontology.AnnotationListingService.listGeneric(AnnotationListingService.groovy:45)

	at GrailsMelodyGrailsPlugin$_closure4_closure16_closure17.doCall(GrailsMelodyGrailsPlugin.groovy:184)

	at be.cytomine.api.ontology.RestAnnotationDomainController.createRequest(RestAnnotationDomainController.groovy:432)

	at be.cytomine.api.ontology.RestAnnotationDomainController.doSearch(RestAnnotationDomainController.groovy:233)

	at be.cytomine.api.ontology.RestAnnotationDomainController.search(RestAnnotationDomainController.groovy:133)

	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)

	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)

	at net.bull.javamelody.JspWrapper.invoke(JspWrapper.java:151)

	at net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:282)

	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:203)

	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:181)

	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)

	at cytomine.web.APIAuthentificationFilters.doFilter(APIAuthentificationFilters.groovy:46)

	at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)

	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.lang.Thread.run(Thread.java:748)

```

**Comment by geektortoise** [comment]
Fixed by https://github.com/cytomine/Cytomine-core/commit/950d2c3bc070fcfda278efa3eb83a066c18e1ee8#diff-c9c9d071d2bf15c9b415c8b1faa7da1dedacb1596f23bdfc38b13ee249a4cbf7
