### ISSUE TITLE
Cytomine Core : Upload image failed

### ISSUE THREAD

**Issue by hervekhg** [cytomine/Cytomine-core-legacy#1203]
Hi,
I've installed Cytomine, all the services (core, ims, iipoff, iipcyto...) is running but when I try to upload image it's failed.
![image](https://user-images.githubusercontent.com/5341737/120440986-660a9100-c384-11eb-84cd-c26b9e205d69.png)

But i can see the image on /data/images on ims containers
![image](https://user-images.githubusercontent.com/5341737/120440896-4ffcd080-c384-11eb-84bc-b710736fe46f.png)

**Below the complete logs of ims when i try to upload a file.**

2021-06-02 06:33:27,837 [http-bio-8081-exec-3] INFO  storage.StorageController  - Upload is made on Cytomine = http://core.cyto89.local
2021-06-02 06:33:27,837 [http-bio-8081-exec-3] INFO  storage.StorageController  - We use "e3c09071-c05b-466e-9218-91d12c560da6"/"5546bb94-269d-4765-b86a-37a4c3b58c45" to connect
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - tryAPIAuthentification
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - cytomineUrl=http://core.cyto89.local
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - ISPubKey="e3c09071-c05b-466e-9218-91d12c560da6"
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - ISPrivKey="5546bb94-269d-4765-b86a-37a4c3b58c45"
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - authorization=CYTOMINE e3c09071-c05b-466e-9218-91d12c560da6:OxBhLvTzry6MQ//y6tj46E2MUbc=
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - host=ims:8081
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - connection=close
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - content-length=648
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - x-request-id=6c59df8f6425cba8912ef4b51490861a
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - x-real-ip=10.96.89.4
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - x-forwarded-for=10.96.89.4
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - x-forwarded-proto=http
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - x-forwarded-host=upload.cyto89.local
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - x-forwarded-port=80
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - x-scheme=http
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - origin=http://core.cyto89.local
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - referer=http://core.cyto89.local/
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19043
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - cache-control=max-age=0
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - accept=application/json, text/plain, */*
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - accept-language=en-US,en;q=0.5
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - authorization=CYTOMINE e3c09071-c05b-466e-9218-91d12c560da6:OxBhLvTzry6MQ//y6tj46E2MUbc=
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - content-type=multipart/form-data; boundary=---------------------------7e519b1b20214
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - content-type-full=null
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - datefull=2021-06-02T06:02:20.308Z
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - accept-encoding=gzip, deflate
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - finalDate=2021-06-02T06:02:20.308Z
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - forwardURI=/upload
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - content_md5=
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - content_type=
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - date=2021-06-02T06:02:20.308Z
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - queryString=?cytomine=http://core.cyto89.local&idStorage=86
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - path=/upload
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - method=POST
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - accessKey=e3c09071-c05b-466e-9218-91d12c560da6
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - Connection Cytomine: http://core.cyto89.local "e3c09071-c05b-466e-9218-91d12c560da6" "5546bb94-269d-4765-b86a-37a4c3b58c45"
2021-06-02 06:33:27,838 [http-bio-8081-exec-3] INFO  web.CytomineService  - cytomine.getUser(e3c09071-c05b-466e-9218-91d12c560da6)
2021-06-02 06:33:27,839 [http-bio-8081-exec-3] INFO  client.HttpClient  - Connection to http://core.cyto89.local/api/user.json?publicKey=e3c09071-c05b-466e-9218-91d12c560da6
2021-06-02 06:33:50,240 [quartzScheduler_Worker-9] INFO  client.Cytomine  - fetchCollection=/api/deletecommand.json?domain=uploadedFile&after=1622442830240&max=0&offset=0
2021-06-02 06:33:50,240 [quartzScheduler_Worker-9] INFO  client.HttpClient  - Connection to http://core:8080/api/deletecommand.json?domain=uploadedFile&after=1622442830240&max=0&offset=0
2021-06-02 06:33:50,248 [quartzScheduler_Worker-9] INFO  client.Cytomine  - 401
2021-06-02 06:33:50,248 [quartzScheduler_Worker-9] INFO  core.JobRunShell  - Job GRAILS_JOBS.ims.DeleteImageFileJob threw a JobExecutionException:
org.quartz.JobExecutionException: java.lang.NullPointerException [See nested exception: java.lang.NullPointerException]
        at grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:111)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NullPointerException
        at be.cytomine.client.collections.Collection.size(Collection.java:66)
        at ims.DeleteImageFileJob.execute(DeleteImageFileJob.groovy:36)
        at grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:104)
        ... 2 more
2021-06-02 06:33:50,248 [quartzScheduler_Worker-9] ERROR listeners.ExceptionPrinterJobListener  - Exception occurred in job: Grails Job
org.quartz.JobExecutionException: java.lang.NullPointerException [See nested exception: java.lang.NullPointerException]
        at grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:111)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NullPointerException
        at be.cytomine.client.collections.Collection.size(Collection.java:66)
        at ims.DeleteImageFileJob.execute(DeleteImageFileJob.groovy:36)
        at grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:104)
        ... 2 more

**Comment by godardt** [comment]
Looks like we are a lot of people running into this issue but never had a response from the devs. Did you manage to fix it?

**Comment by geektortoise** [comment]
Hello, 
I'm no more on this project.
However, a new version of Cytomine has been released with a new Core (this one is the legacy).
Does the problem still occur ?
