### ISSUE TITLE
HTTP Apache client error when asking cropAlpha on some machine

### ISSUE THREAD

**Issue by geektortoise** [cytomine/Cytomine-core-legacy#1222]
In some case (always reproductible in the concerned machine but not reproductible on all machine), there is a bug when asking crop of an alphamask

The origin of the error seems to come from the org.apache http client and a conflict in multiple versions of it : https://stackoverflow.com/questions/28474486/httpclient-post-call-failing-from-a-servlet-with-error-java-lang-nosuchmethoderr

```
24-06-2022 12:06:41,010 ERROR GrailsExceptionResolver - NoSuchMethodError occurred when processing request: [GET] /api/userannotation/2041/alphamask.png
org.apache.http.entity.StringEntity.<init>(Ljava/lang/String;Lorg/apache/http/entity/ContentType;)V. Stacktrace follows:
org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [cropAlphaMask] of controller [be.cytomine.api.ontology.RestUserAnnotationController]  caused exception: Runtime error executing action
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
	at cytomine.web.APIAuthentificationFilters.doFilter(APIAuthentificationFilters.groovy:46)
	at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Runtime error executing action
	... 7 more
Caused by: java.lang.reflect.InvocationTargetException
	... 7 more
Caused by: java.lang.NoSuchMethodError: org.apache.http.entity.StringEntity.<init>(Ljava/lang/String;Lorg/apache/http/entity/ContentType;)V
	at org.apache.http.client.entity.UrlEncodedFormEntity.<init>(UrlEncodedFormEntity.java:61)
	at groovyx.net.http.EncoderRegistry.encodeForm(EncoderRegistry.java:227)
	at groovyx.net.http.HTTPBuilder$RequestConfigDelegate.setBody(HTTPBuilder.java:1200)
	at groovyx.net.http.HTTPBuilder$RequestConfigDelegate.setPropertiesFromMap(HTTPBuilder.java:1111)
	at groovyx.net.http.HTTPBuilder.post(HTTPBuilder.java:354)
	at be.cytomine.middleware.ImageServerService.makeRequest(ImageServerService.groovy:354)
	at be.cytomine.middleware.ImageServerService.crop(ImageServerService.groovy:244)
	at be.cytomine.middleware.ImageServerService.crop(ImageServerService.groovy:176)
	at be.cytomine.middleware.ImageServerService.crop(ImageServerService.groovy:168)
	at be.cytomine.api.ontology.RestUserAnnotationController.cropAlphaMask(RestUserAnnotationController.groovy:335)
	... 7 more
```
## How to reproduce 
- Unzip the following bootstrap somewhere (/tmp is good for testing) [Cytomine-bootstrap.zip](https://github.com/cytomine/Cytomine-core/files/8976342/Cytomine-bootstrap.zip)
- Restore the following backup [BU.zip](https://github.com/cytomine/Cytomine-core/files/8976303/BU.zip)
- Download the https://cytomine.com/collection/cmu-1/cmu-1-ndpi image and set it at the location /data/images/58/1655987530869/.
- Run the restart.sh file
- Admin password is in the core config file
- Relaunch the last job in the "test" project.

It works on my machine but not on @chlmarchal one.

Can you try to compile core 3.2.2 to check if there is no compilation error on a clean machine ?

**Comment by geektortoise** [comment]
The considered line 
https://github.com/cytomine/Cytomine-core/blob/master/grails-app/services/be/cytomine/middleware/ImageServerService.groovy#L354

**Comment by loic911** [comment]
**Problem**: we import httpclient directly from Jar file while a library imports it using maven dependencies. Version conflict.
**Resolved**: by ignoring the version from the dependency (https://github.com/cytomine/Cytomine-core/commit/2c8dc37d235a2197465aada2a43fcf9865f724d1)
**Remarks**: this is just a temp workaround, as, for the spring core version we won't import jar file directly anymore.
