### ISSUE TITLE
[CYTO-921] Upload image SEC_USER

### ISSUE THREAD

**Issue by stevben** [cytomine/Cytomine-core-legacy#201]
<b><i>[reporter="stevben", created="lun., 13 mai 2013 15:44:07 +0200", resolved="mar., 21 mai 2013 11:20:42 +0200"]</i></b>

<p>Errors ACL</p>

**Comment by stevben** [comment]
<b><i>[author="stevben", created="lun., 13 mai 2013 15:47:28 +0200"]</i></b>

<p>Invalid path: 'project.id' [select distinct storage from org.codehaus.groovy.grails.plugins.springsecurity.acl.AclObjectIdentity as aclObjectId, org.codehaus.groovy.grails.plugins.springsecurity.acl.AclEntry as aclEntry, org.codehaus.groovy.grails.plugins.springsecurity.acl.Acl<br/>
Sid as aclSid, be.cytomine.security.SecUser as secUser, be.cytomine.image.server.Storage as storage where aclObjectId.objectId = project.id and aclEntry.aclObjectIdentity = aclObjectId.id and aclEntry.sid = aclSid.id and aclSid.sid like 'xmoleslopez']. Stacktrace follows:<br/>
org.hibernate.hql.ast.QuerySyntaxException: Invalid path: 'project.id' [select distinct storage from org.codehaus.groovy.grails.plugins.springsecurity.acl.AclObjectIdentity as aclObjectId, org.codehaus.groovy.grails.plugins.springsecurity.acl.AclEntry as aclEntry, org.codehaus.<br/>
groovy.grails.plugins.springsecurity.acl.AclSid as aclSid, be.cytomine.security.SecUser as secUser, be.cytomine.image.server.Storage as storage where aclObjectId.objectId = project.id and aclEntry.aclObjectIdentity = aclObjectId.id and aclEntry.sid = aclSid.id and aclSid.sid li<br/>
ke 'xmoleslopez']<br/>
    at be.cytomine.SecurityACL.getStorageList(SecurityACL.groovy:72)<br/>
    at be.cytomine.image.server.StorageService.list(StorageService.groovy:24)<br/>
    at be.cytomine.api.image.server.RestStorageController$_closure1.doCall(RestStorageController.groovy:18)<br/>
    at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:195)<br/>
    at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)<br/>
    at cytomine.web.APIAuthentificationFilters.doFilter(APIAuthentificationFilters.groovy:24)<br/>
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/>
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/>
    at java.lang.Thread.run(Thread.java:722)</p>

**Comment by stevben** [comment]
<b><i>[author="stevben", created="lun., 13 mai 2013 15:48:53 +0200"]</i></b>

<p>13-05-2013 11:58:53,414 ERROR GrailsExceptionResolver - GroovyCastException occurred when processing request: <span class="error">&#91;POST&#93;</span> /api/uploadedfile<br/>
Cannot cast object 'null' with class 'null' to class 'int'. Try 'java.lang.Integer' instead. Stacktrace follows:<br/>
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'null' with class 'null' to class 'int'. Try 'java.lang.Integer' instead<br/>
    at be.cytomine.api.image.RestUploadedFileController$_closure3.doCall(RestUploadedFileController.groovy:59)<br/>
    at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:195)<br/>
    at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)<br/>
    at cytomine.web.APIAuthentificationFilters.doFilter(APIAuthentificationFilters.groovy:24)<br/>
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/>
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/>
    at java.lang.Thread.run(Thread.java:722)</p>

**Comment by stevben** [comment]
<b><i>[author="rmaree", created="mar., 21 mai 2013 09:26:48 +0200"]</i></b>

<p>Problème rencontré aussi par N.Tréségnie: liste de storage vide</p>

**Comment by stevben** [comment]
<b><i>[author="stevben", created="mar., 21 mai 2013 11:20:38 +0200"]</i></b>

<p>Problème déjà fixé. Sera réglé au prochain déploiement.</p>
