### ISSUE TITLE
[CYTO-745] Annotation object has no attribute area

### ISSUE THREAD

**Issue by stevben** [cytomine/Cytomine-core-legacy#375]
<b><i>[reporter="rmaree", created="jeu., 29 nov. 2012 12:39:29 +0100", resolved="jeu., 21 févr. 2013 11:26:32 +0100"]</i></b>

<p>J'ai ce message d'erreur lors du dump annotations depuis le client python:</p>

<p>Annotation 2: id: 8850917  |<br/>
Traceback (most recent call last):<br/>
  File "add_and_run_job.py", line 320, in <module><br/>
    main(sys.argv<span class="error">&#91;1:&#93;</span>)<br/>
  File "add_and_run_job.py", line 225, in main<br/>
    annotations = conn.dumpAnnotations(annotations = annotations, get_image_url_func = Annotation.get_annotation_alpha_crop_url, dest_path = pyxit_parameters<span class="error">&#91;&#39;dir_ls&#39;&#93;</span>, excluded_terms = excluded_terms, desired_zoom = dump_zoom)<br/>
  File "/home/maree/CYTOMINE/cytomine/cytomine-datamining/applications/segmentation_model_builder/trunk/src/cytomine/cytomine.py", line 575, in dumpAnnotations<br/>
    if annotation.area == 0:<br/>
AttributeError: 'Annotation' object has no attribute 'area'</p>

<p>Pourtant l'annotation en question a bien un champ area si je passe par <a href="http://beta.cytomine.be/api/annotation/8850917.json:" class="external-link">http://beta.cytomine.be/api/annotation/8850917.json:</a></p>

{"class":"be.cytomine.ontology.UserAnnotation","id":8850917,"location":"POLYGON ((155385 74665, 155385 74751, 155475 74751, 155475 74665, 155385 74665))","image":728755,"geometryCompression":0,"project":716498,"container":716498,"user":14,"nbComments":0,"area":1780,"perimeter":81,"centroid":
{"x":155430,"y":74708}

<p>,"created":"1354169730772","updated":null,"term":<span class="error">&#91;8844845&#93;</span>,"userByTerm":[</p>

{"id":8863283,"term":8844845,"user":[14]}

<p>],"cropURL":"http://beta.cytomine.be/api/userannotation/8850917/crop.jpg","smallCropURL":"http://beta.cytomine.be/api/userannotation/8850917/crop.jpg?max_size=256","url":"http://beta.cytomine.be/api/userannotation/8850917/crop.jpg","imageURL":"http://beta.cytomine.be/#tabs-image-716498-728755-8850917","reviewed":false}</p>

**Comment by stevben** [comment]
<b><i>[author="lrollus", created="jeu., 29 nov. 2012 13:17:47 +0100"]</i></b>

<p>On ne les mets pour l'instant pas dans les listings pour ne pas surcharger la requête (et un peu le json). <br/>
Je testerais si le fait de les ajouter en calculant lors de la requête les area, perim, centroid,etc... ne surcharge pas les services de listing;</p>

<p>C'est normale que l'annotation ait le champs area/perim car c'est une "simple" consultation et pas une consultation d'une annotation parmi un listing.</p>

**Comment by stevben** [comment]
<b><i>[author="stevben", created="mar., 8 janv. 2013 14:44:47 +0100"]</i></b>

<p>Problème du client Python dans ce cas.</p>

<p>Cependant, il faudrait pouvoir demander de les inclure via une queryString.</p>

<p>Vérifier comment fonctionne compute term area comment ça marche.</p>
