### ISSUE TITLE
[CYTO-573] Tester les services d'upload de fichiers

### ISSUE THREAD

**Issue by stevben** [cytomine/Cytomine-core-legacy#542]
<b><i>[reporter="lrollus", created="ven., 6 avr. 2012 10:29:20 +0200"]</i></b>

**Comment by stevben** [comment]
<b><i>[author="rmaree", created="jeu., 24 janv. 2013 11:01:31 +0100"]</i></b>

<p>À améliorer:</p>

<ul class="alternate" type="square">
    <li>Client upload qui envoie simplement les fichiers, conversion (e.g. ndpi2svs) faite sur le serveur et non le client</li>
</ul>

<ul class="alternate" type="square">
    <li>Upload de formats avec multiples fichiers (ex: mrxs)</li>
</ul>

<p>Bugs:</p>

<ul class="alternate" type="square">
    <li>Transferts de fichiers (tif, svs) qui ne se terminent jamais dans l'interface web: fichier n'apparaît pas dans la liste des "uploaded files"<br/>
et aucune trace du fichier dans /var/log/tomcat7/catalina.out de 10.1.0.101<br/>
Limite sur taille de fichier  (en l'occurence ici ~ 2Go) ? Autre explication ?<br/>
Erreur 500 dans le client Python et log grails:<br/>
2013-01-24 12:36:08,337 <span class="error">&#91;http-bio-8080-exec-552&#93;</span> INFO  web.RequestFilters  - errors.error500: user:14<br/>
2013-01-24 12:36:08,341 <span class="error">&#91;http-bio-8080-exec-552&#93;</span> INFO  web.RequestFilters  - errors.error500 Request took 4ms</li>
</ul>

<ul class="alternate" type="square">
    <li>Fichiers SVS (e.g. mrxs convertis avec Aperio Digital Scope) qui restent indéfiniment en statut "converted"<br/>
2013-01-24 10:12:14,090 <a href="#1)">BackgroundThreadManager Thread (BG#1)</a> INFO  web.ImagePropertiesService  - 14/1359018691615/A12_192_Sox9.svs : <a href="http://is34.cytomine.be/fcgi-bin/iipsrv.fcgi?FIF=/opt/cytomine/storage/beta.cytomine.be/14/135901" class="external-link">http://is34.cytomine.be/fcgi-bin/iipsrv.fcgi?FIF=/opt/cytomine/storage/beta.cytomine.be/14/135901\</a><br/>
8691615/A12_192_Sox9.svs&obj=Image-Properties<br/>
2013-01-24 10:12:14,550 <a href="#1)">BackgroundThreadManager Thread (BG#1)</a> INFO  web.ImagePropertiesService  - extract properties from svs : 14/1359018691615/A12_192_Sox9.svs<br/>
2013-01-24 10:12:14,632 <a href="#1)">BackgroundThreadManager Thread (BG#1)</a> INFO  web.ImagePropertiesService  - magnificationProperty=be.cytomine.image.server.ImageProperty : 9302662<br/>
2013-01-24 10:12:14,690 <a href="#1)">BackgroundThreadManager Thread (BG#1)</a> INFO  web.ImagePropertiesService  - widthProperty=be.cytomine.image.server.ImageProperty : 9302670<br/>
2013-01-24 10:12:14,747 <a href="#1)">BackgroundThreadManager Thread (BG#1)</a> INFO  web.ImagePropertiesService  - heightProperty=be.cytomine.image.server.ImageProperty : 9302667<br/>
2013-01-24 10:12:14,844 <a href="#1)">BackgroundThreadManager Thread (BG#1)</a> ERROR BackgroundExceptionHandler  - Unhandled failure while processing BackgroundThreadManager Thread (BG#1)<br/>
java.lang.NumberFormatException: For input string: "0,22109"<br/>
at java.lang.Float.parseFloat(Float.java:452)<br/>
at cytomine.web.ImagePropertiesService.extractUsefulSVS(ImagePropertiesService.groovy:186)<br/>
at cytomine.web.ImagePropertiesService.extractUseful(ImagePropertiesService.groovy:73)<br/>
at be.cytomine.DeployImagesService.deployUploadedFile(DeployImagesService.groovy:75)<br/>
at be.cytomine.api.image.RestUploadedFileController$_closure4_closure6.doCall(RestUploadedFileController.groovy:105)<br/>
at BackgroundService$_execute_closure1.doCall(BackgroundService.groovy:13)<br/>
at BackgroundThreadManager$1.run(BackgroundThreadManager.java:96)<br/>
at java.lang.Thread.run(Thread.java:722)</li>
</ul>
