### ISSUE TITLE
[CYTO-500] UserPosition: erreur dans les logs

### ISSUE THREAD

**Issue by stevben** [cytomine/Cytomine-core-legacy#615]
<b><i>[reporter="lrollus", created="jeu., 22 mars 2012 08:42:34 +0100", resolved="lun., 26 mars 2012 14:54:17 +0200"]</i></b>

<p>Il y a quelques erreurs dans les logs:</p>

<p>ERROR  performExecutions, Could not synchronize database state with session<br/>
org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): <a href="#391201">be.cytomine.social.UserPosition#391201</a><br/>
    at org.hibernate.persister.entity.AbstractEntityPersister.check(AbstractEntityPersister.java:1792)<br/>
    at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:2435)<br/>
    at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:2335)<br/>
    at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:2635)</p>

**Comment by stevben** [comment]
<b><i>[author="lrollus", created="jeu., 22 mars 2012 08:43:43 +0100"]</i></b>

<p>2012-03-22 06:58:13,863 <span class="error">&#91;http-8080-3&#93;</span> INFO  web.RequestFilters  - restUserPosition.add: user:14 request=| PARAM=| POST=</p>

{"lon":1288,"zoom":4,"image":12471,"lat":966}

<p> | <br/>
org.apache.commons.lang.UnhandledException: org.codehaus.groovy.grails.web.converters.exceptions.ConverterException: org.hibernate.LazyInitializationException: could not initialize proxy - no Session<br/>
    at org.codehaus.groovy.grails.web.converters.AbstractConverter.toString(AbstractConverter.java:39)<br/>
    at org.codehaus.groovy.grails.web.converters.AbstractConverter$toString.call(Unknown Source)<br/>
    at org.codehaus.groovy.grails.plugins.converters.codecs.JSONCodec$_<em>clinit</em>_closure1.doCall(JSONCodec.groovy:27)<br/>
    at sun.reflect.GeneratedMethodAccessor552.invoke(Unknown Source)<br/>
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
    at java.lang.reflect.Method.invoke(Method.java:616)</p>

**Comment by stevben** [comment]
<b><i>[author="lrollus", created="jeu., 22 mars 2012 08:45:17 +0100"]</i></b>

<p>La même erreur que "LazyInitializationException: could not initialize proxy - no Session" est déclenché pour le retrieval</p>
