### ISSUE TITLE
[CYTO-475] GET annotation by project and term: org.postgresql.util.PSQLException: ERREUR: erreur de syntaxe sur ou près de « ) »

### ISSUE THREAD

**Issue by stevben** [cytomine/Cytomine-core-legacy#640]
<b><i>[reporter="lrollus", created="ven., 27 janv. 2012 09:51:09 +0100", resolved="mar., 17 avr. 2012 14:35:54 +0200"]</i></b>

<p>Le 23/01 vers 0h15<br/>
Le 23/01 vers 12h23<br/>
Énormément d'exception "PSQLException" survenue (plusieurs par secondes sur quelques minutes).<br/>
Impossible a reproduire pour ma part. </p>

<p>2012-01-23 00:16:41,928 <span class="error">&#91;http-8080-8&#93;</span> INFO  ontology.RestAnnotationController  - annotationService.list: ULB-ANAPATH-LBA-PAPA # Vaisseau sanguin # []<br/>
INFO   call, errors.error500 Request took 1182ms<br/>
2012-01-23 00:16:41,929 <span class="error">&#91;http-8080-1&#93;</span> INFO  web.RequestFilters  - errors.error500 Request took 1182ms<br/>
INFO   call, errors.error500 Request took 1183ms<br/>
2012-01-23 00:16:41,930 <span class="error">&#91;http-8080-1&#93;</span> INFO  web.RequestFilters  - errors.error500 Request took 1183ms<br/>
ERROR  resolveException, Exception occurred when processing request: <span class="error">&#91;GET&#93;</span> /api/term/4751/project/65/annotation.json<br/>
Stacktrace follows:<br/>
org.postgresql.util.PSQLException: ERREUR: erreur de syntaxe sur ou près de « ) »<br/>
  Position : 1000<br/>
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)<br/>
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)<br/>
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)<br/>
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)<br/>
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388)<br/>
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:273)<br/>
    at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)<br/>
    at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)<br/>
    at grails.orm.HibernateCriteriaBuilder.invokeMethod(HibernateCriteriaBuilder.java:1163)<br/>
    at be.cytomine.ontology.AnnotationService.list(AnnotationService.groovy:134)<br/>
    at be.cytomine.ontology.AnnotationService$$FastClassByCGLIB$$27672c46.invoke(<generated&gt<img class="emoticon" src="http://jira.cytomine.be/images/icons/emoticons/wink.gif" height="20" width="20" align="absmiddle" alt="" border="0"/><br/>
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:149)<br/>
    at be.cytomine.ontology.AnnotationService$$EnhancerByCGLIB$$cd6850fc.list(<generated&gt<img class="emoticon" src="http://jira.cytomine.be/images/icons/emoticons/wink.gif" height="20" width="20" align="absmiddle" alt="" border="0"/><br/>
    at be.cytomine.ontology.AnnotationService$$FastClassByCGLIB$$27672c46.invoke(<generated&gt<img class="emoticon" src="http://jira.cytomine.be/images/icons/emoticons/wink.gif" height="20" width="20" align="absmiddle" alt="" border="0"/><br/>
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:149)<br/>
    at be.cytomine.ontology.AnnotationService$$EnhancerByCGLIB$$6591fb3.list(<generated&gt<img class="emoticon" src="http://jira.cytomine.be/images/icons/emoticons/wink.gif" height="20" width="20" align="absmiddle" alt="" border="0"/><br/>
    at GrailsMelodyGrailsPlugin$_closure5_closure18_closure19.doCall(GrailsMelodyGrailsPlugin.groovy:165)<br/>
    at be.cytomine.api.ontology.RestAnnotationController$_closure7.doCall(RestAnnotationController.groovy:107)<br/>
    at be.cytomine.api.ontology.RestAnnotationController$_closure7.doCall(RestAnnotationController.groovy)<br/>
    at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:115)<br/>
    at java.lang.Thread.run(Thread.java:679)<br/>
2012-01-23 00:16:39,561 <span class="error">&#91;http-8080-3&#93;</span> ERROR errors.GrailsExceptionResolver  - Exception occurred when processing request: <span class="error">&#91;GET&#93;</span> /api/term/4751/project/65/annotation.json<br/>
Stacktrace follows:<br/>
org.postgresql.util.PSQLException: ERREUR: erreur de syntaxe sur ou près de « ) »<br/>
  Position : 1000<br/>
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)<br/>
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)<br/>
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)<br/>
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)<br/>
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388)<br/>
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:273)<br/>
    at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)<br/>
    at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)<br/>
    at grails.orm.HibernateCriteriaBuilder.invokeMethod(HibernateCriteriaBuilder.java:1163)<br/>
    at be.cytomine.ontology.AnnotationService.list(AnnotationService.groovy:134)<br/>
    at be.cytomine.ontology.AnnotationService$$FastClassByCGLIB$$27672c46.invoke(<generated&gt<img class="emoticon" src="http://jira.cytomine.be/images/icons/emoticons/wink.gif" height="20" width="20" align="absmiddle" alt="" border="0"/><br/>
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:149)<br/>
    at be.cytomine.ontology.AnnotationService$$EnhancerByCGLIB$$cd6850fc.list(<generated&gt<img class="emoticon" src="http://jira.cytomine.be/images/icons/emoticons/wink.gif" height="20" width="20" align="absmiddle" alt="" border="0"/><br/>
    at be.cytomine.ontology.AnnotationService$$FastClassByCGLIB$$27672c46.invoke(<generated&gt<img class="emoticon" src="http://jira.cytomine.be/images/icons/emoticons/wink.gif" height="20" width="20" align="absmiddle" alt="" border="0"/><br/>
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:149)<br/>
    at be.cytomine.ontology.AnnotationService$$EnhancerByCGLIB$$6591fb3.list(<generated&gt<img class="emoticon" src="http://jira.cytomine.be/images/icons/emoticons/wink.gif" height="20" width="20" align="absmiddle" alt="" border="0"/><br/>
    at GrailsMelodyGrailsPlugin$_closure5_closure18_closure19.doCall(GrailsMelodyGrailsPlugin.groovy:165)<br/>
    at be.cytomine.api.ontology.RestAnnotationController$_closure7.doCall(RestAnnotationController.groovy:107)<br/>
    at be.cytomine.api.ontology.RestAnnotationController$_closure7.doCall(RestAnnotationController.groovy)<br/>
    at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:115)<br/>
    at java.lang.Thread.run(Thread.java:679)</p>

**Comment by stevben** [comment]
<b><i>[author="stevben", created="lun., 16 avr. 2012 16:38:08 +0200"]</i></b>

<p>problème de critère GROM inLIST dont la liste est soit nulle, soit une collection vide</p>

**Comment by stevben** [comment]
<b><i>[author="stevben", created="mar., 17 avr. 2012 14:35:51 +0200"]</i></b>

<p>A été fixé lors de la réécriture des méthodes pour filtre par images</p>
