### ISSUE TITLE
[CYTO-473] Bug avec term:  org.hibernate.StaleObjectStateException

### ISSUE THREAD

**Issue by stevben** [cytomine/Cytomine-core-legacy#642]
<b><i>[reporter="lrollus", created="ven., 20 janv. 2012 08:28:45 +0100", resolved="ven., 20 janv. 2012 09:44:34 +0100"]</i></b>

<p>[ 18.01.12 11:47:31.401] <span class="error">&#91;http-8080-1&#93;</span><br/>
ERROR<br/>
org.codehaus.groovy.grails.orm.hibernate.events.PatchedDefaultFlushEventListener<br/>
org.codehaus.groovy.grails.orm.hibernate.events.PatchedDefaultFlushEventListener</p>

<p> Could not synchronize database state with session</p>

<p>org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): <a href="#4762">be.cytomine.ontology.Term#4762</a><br/>
       at org.hibernate.persister.entity.AbstractEntityPersister.check(AbstractEntityPersister.java:1792)<br/>
       at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:2435)<br/>
       at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:2335)<br/>
       at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:2635)<br/>
       at org.hibernate.action.EntityUpdateAction.execute(EntityUpdateAction.java:115)<br/>
       at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:279)<br/>
       at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:263)<br/>
       at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:168)<br/>
       at org.codehaus.groovy.grails.orm.hibernate.events.PatchedDefaultFlushEventListener.performExecutions(PatchedDefaultFlushEventListener.java:46)<br/>
       at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:50)<br/>
       at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1027)<br/>
       at org.springframework.orm.hibernate3.HibernateTemplate$28.doInHibernate(HibernateTemplate.java:883)<br/>
       at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:406)<br/>
       at org.springframework.orm.hibernate3.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:374)<br/>
       at org.springframework.orm.hibernate3.HibernateTemplate.flush(HibernateTemplate.java:881)<br/>
       at org.springframework.orm.hibernate3.HibernateOperations$flush.call(Unknown Source)<br/>
       at org.codehaus.groovy.grails.plugins.orm.hibernate.HibernatePluginSupport$_addBasicPersistenceMethods_closure78.doCall(HibernatePluginSupport.groovy:850)<br/>
       at sun.reflect.GeneratedMethodAccessor2326.invoke(Unknown Source)<br/>
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
       at java.lang.reflect.Method.invoke(Method.java:616)<br/>
       at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)<br/>
       at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:80)<br/>
       at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:307)<br/>
       at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:63)<br/>
       at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)<br/>
       at be.cytomine.ontology.AnnotationTerm.unlink(AnnotationTerm.groovy:96)<br/>
       at be.cytomine.ontology.AnnotationTerm$unlink.call(Unknown Source)<br/>
       at be.cytomine.ontology.AnnotationTermService.destroy(AnnotationTermService.groovy:185)<br/>
       at sun.reflect.GeneratedMethodAccessor2329.invoke(Unknown Source)<br/>
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
       at java.lang.reflect.Method.invoke(Method.java:616)<br/>
       at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)<br/>
       at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)<br/>
       at groovy.lang.MetaMethod$doMethodInvoke.call(Unknown Source)<br/>
       at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:40)<br/>
       at groovy.lang.MetaMethod$doMethodInvoke.call(Unknown Source)<br/>
       at GrailsMelodyGrailsPlugin$_closure5_closure18_closure19.doCall(GrailsMelodyGrailsPlugin.groovy:165)<br/>
       at sun.reflect.GeneratedMethodAccessor190.invoke(Unknown Source)<br/>
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
       at java.lang.reflect.Method.invoke(Method.java:616)<br/>
       at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)<br/>
       at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:80)<br/>
       at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1068)<br/>
       at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:886)<br/>
       at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)<br/>
       at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)<br/>
       at be.cytomine.command.DeleteCommand.execute(DeleteCommand.groovy:34)<br/>
       at be.cytomine.command.DeleteCommand$execute.call(Unknown Source)<br/>
       at be.cytomine.CommandService.processCommand(CommandService.groovy:49)<br/>
       at be.cytomine.CommandService$processCommand.callCurrent(Unknown Source)<br/>
       at be.cytomine.CommandService.processCommand(CommandService.groovy:36)<br/>
       at be.cytomine.CommandService$$FastClassByCGLIB$$744b7e49.invoke(<generated&gt<img class="emoticon" src="http://jira.cytomine.be/images/icons/emoticons/wink.gif" height="20" width="20" align="absmiddle" alt="" border="0"/><br/>
       at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:149)<br/>
       at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:688)<br/>
       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)<br/>
       at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)<br/>
       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)<br/>
       at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621)<br/>
       at be.cytomine.CommandService$$EnhancerByCGLIB$$e1a863dd.processCommand(<generated&gt<img class="emoticon" src="http://jira.cytomine.be/images/icons/emoticons/wink.gif" height="20" width="20" align="absmiddle" alt="" border="0"/><br/>
       at sun.reflect.GeneratedMethodAccessor2312.invoke(Unknown Source)<br/>
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
       at java.lang.reflect.Method.invoke(Method.java:616)<br/>
       at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)<br/>
       at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)<br/>
       at groovy.lang.MetaMethod$doMethodInvoke.call(Unknown Source)<br/>
       at GrailsMelodyGrailsPlugin$_closure5_closure18_closure19.doCall(GrailsMelodyGrailsPlugin.groovy:165)<br/>
       at sun.reflect.GeneratedMethodAccessor190.invoke(Unknown Source)<br/>
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
       at java.lang.reflect.Method.invoke(Method.java:616)<br/>
       at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)<br/>
       at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:80)<br/>
       at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1068)<br/>
       at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:886)<br/>
       at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)<br/>
       at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)<br/>
       at be.cytomine.ModelService.executeCommand(ModelService.groovy:59)<br/>
       at sun.reflect.GeneratedMethodAccessor1027.invoke(Unknown Source)<br/>
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
       at java.lang.reflect.Method.invoke(Method.java:616)<br/>
       at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:266)<br/>
       at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:51)<br/>
       at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:153)<br/>
       at be.cytomine.ontology.AnnotationTermService.deleteAnnotationTerm(AnnotationTermService.groovy:105)<br/>
       at sun.reflect.GeneratedMethodAccessor3845.invoke(Unknown Source)<br/>
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
       at java.lang.reflect.Method.invoke(Method.java:616)<br/>
       at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)<br/>
       at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)<br/>
       at groovy.lang.MetaMethod$doMethodInvoke.call(Unknown Source)<br/>
       at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:40)<br/>
       at org.codehaus.groovy.runtime.dgm$32$doMethodInvoke.call(Unknown Source)<br/>
       at GrailsMelodyGrailsPlugin$_closure5_closure18_closure19.doCall(GrailsMelodyGrailsPlugin.groovy:165)<br/>
       at sun.reflect.GeneratedMethodAccessor190.invoke(Unknown Source)<br/>
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
       at java.lang.reflect.Method.invoke(Method.java:616)<br/>
       at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)<br/>
       at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:80)<br/>
       at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1068)<br/>
       at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:886)<br/>
       at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1003)<br/>
       at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1070)<br/>
       at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:886)<br/>
       at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)<br/>
       at be.cytomine.ontology.AnnotationTermService$_deleteAnnotationTermFromUser_closure2.doCall(AnnotationTermService.groovy:119)<br/>
       at sun.reflect.GeneratedMethodAccessor8188.invoke(Unknown Source)<br/>
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
       at java.lang.reflect.Method.invoke(Method.java:616)<br/>
       at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)<br/>
       at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)<br/>
       at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1058)<br/>
       at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1070)<br/>
       at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:886)<br/>
       at groovy.lang.Closure.call(Closure.java:282)<br/>
       at groovy.lang.Closure.call(Closure.java:295)<br/>
       at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1220)<br/>
       at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1196)<br/>
       at org.codehaus.groovy.runtime.dgm$110.invoke(Unknown Source)<br/>
       at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:270)<br/>
       at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:52)<br/>
       at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)<br/>
       at be.cytomine.ontology.AnnotationTermService.deleteAnnotationTermFromUser(AnnotationTermService.groovy:117)<br/>
       at be.cytomine.ontology.AnnotationTermService$deleteAnnotationTermFromUser.callCurrent(Unknown Source)<br/>
       at be.cytomine.ontology.AnnotationTermService.addWithDeletingOldTerm(AnnotationTermService.groovy:85)<br/>
       at be.cytomine.ontology.AnnotationTermService$$FastClassByCGLIB$$f254bdba.invoke(<generated&gt<img class="emoticon" src="http://jira.cytomine.be/images/icons/emoticons/wink.gif" height="20" width="20" align="absmiddle" alt="" border="0"/><br/>
       at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:149)<br/>
       at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:688)<br/>
       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)<br/>
       at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)<br/>
       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)<br/>
       at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621)<br/>
       at be.cytomine.ontology.AnnotationTermService$$EnhancerByCGLIB$$b0f7bdf8.addWithDeletingOldTerm(<generated&gt<img class="emoticon" src="http://jira.cytomine.be/images/icons/emoticons/wink.gif" height="20" width="20" align="absmiddle" alt="" border="0"/><br/>
       at be.cytomine.ontology.AnnotationTermService$$FastClassByCGLIB$$f254bdba.invoke(<generated&gt<img class="emoticon" src="http://jira.cytomine.be/images/icons/emoticons/wink.gif" height="20" width="20" align="absmiddle" alt="" border="0"/><br/>
       at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:149)<br/>
       at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:688)<br/>
       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)<br/>
       at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:67)<br/>
       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)<br/>
       at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621)<br/>
       at be.cytomine.ontology.AnnotationTermService$$EnhancerByCGLIB$$5bc2b947.addWithDeletingOldTerm(<generated&gt<img class="emoticon" src="http://jira.cytomine.be/images/icons/emoticons/wink.gif" height="20" width="20" align="absmiddle" alt="" border="0"/><br/>
       at sun.reflect.GeneratedMethodAccessor8129.invoke(Unknown Source)<br/>
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
       at java.lang.reflect.Method.invoke(Method.java:616)<br/>
       at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)<br/>
       at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)<br/>
       at groovy.lang.MetaMethod$doMethodInvoke.call(Unknown Source)<br/>
       at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:40)<br/>
       at groovy.lang.MetaMethod$doMethodInvoke.call(Unknown Source)<br/>
       at GrailsMelodyGrailsPlugin$_closure5_closure18_closure19.doCall(GrailsMelodyGrailsPlugin.groovy:165)<br/>
       at sun.reflect.GeneratedMethodAccessor190.invoke(Unknown Source)<br/>
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
       at java.lang.reflect.Method.invoke(Method.java:616)<br/>
       at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)<br/>
       at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:80)<br/>
       at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1068)<br/>
       at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:886)<br/>
       at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)<br/>
       at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)<br/>
       at be.cytomine.api.ontology.RestAnnotationTermController$_closure7.doCall(RestAnnotationTermController.groovy:104)<br/>
       at sun.reflect.GeneratedMethodAccessor8187.invoke(Unknown Source)<br/>
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
       at java.lang.reflect.Method.invoke(Method.java:616)<br/>
       at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:225)<br/>
       at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:51)<br/>
       at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)<br/>
       at be.cytomine.api.ontology.RestAnnotationTermController$_closure7.doCall(RestAnnotationTermController.groovy)<br/>
       at sun.reflect.GeneratedMethodAccessor8186.invoke(Unknown Source)<br/>
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
       at java.lang.reflect.Method.invoke(Method.java:616)<br/>
       at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)<br/>
       at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)<br/>
       at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1058)<br/>
       at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1070)<br/>
       at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:886)<br/>
       at groovy.lang.Closure.call(Closure.java:282)<br/>
       at groovy.lang.Closure.call(Closure.java:277)<br/>
       at org.codehaus.groovy.grails.web.servlet.mvc.SimpleGrailsControllerHelper.handleAction(SimpleGrailsControllerHelper.java:368)<br/>
       at org.codehaus.groovy.grails.web.servlet.mvc.SimpleGrailsControllerHelper.executeAction(SimpleGrailsControllerHelper.java:232)<br/>
       at org.codehaus.groovy.grails.web.servlet.mvc.SimpleGrailsControllerHelper.handleURI(SimpleGrailsControllerHelper.java:190)<br/>
       at org.codehaus.groovy.grails.web.servlet.mvc.SimpleGrailsControllerHelper.handleURI(SimpleGrailsControllerHelper.java:129)<br/>
       at org.codehaus.groovy.grails.web.servlet.mvc.SimpleGrailsController.handleRequest(SimpleGrailsController.java:73)<br/>
       at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)<br/>
       at org.codehaus.groovy.grails.web.servlet.GrailsDispatcherServlet.doDispatch(GrailsDispatcherServlet.java:292)<br/>
       at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)<br/>
       at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)<br/>
       at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:560)<br/>
       at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)<br/>
       at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)<br/>
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)<br/>
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)<br/>
       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:70)<br/>
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)<br/>
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)<br/>
       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:70)<br/>
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)<br/>
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)<br/>
       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:70)<br/>
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)<br/>
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)<br/>
       at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:646)<br/>
       at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:436)<br/>
       at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:374)<br/>
       at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:302)<br/>
       at org.codehaus.groovy.grails.web.util.WebUtils.forwardRequestForUrlMappingInfo(WebUtils.java:298)<br/>
       at org.codehaus.groovy.grails.web.util.WebUtils.forwardRequestForUrlMappingInfo(WebUtils.java:264)<br/>
       at org.codehaus.groovy.grails.web.util.WebUtils.forwardRequestForUrlMappingInfo(WebUtils.java:255)<br/>
       at org.codehaus.groovy.grails.web.mapping.filter.UrlMappingsFilter.doFilterInternal(UrlMappingsFilter.java:183)<br/>
       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)<br/>
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)<br/>
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)<br/>
       at org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter.obtainContent(GrailsPageFilter.java:245)<br/>
       at org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter.doFilter(GrailsPageFilter.java:134)<br/>
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)<br/>
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)<br/>
       at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:115)<br/>
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)<br/>
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)<br/>
       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:343)<br/>
       at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:109)<br/>
       at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)<br/>
       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:355)<br/>
       at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:97)<br/>
       at org.springframework.security.web.FilterChainProxy$Virt</p>

**Comment by stevben** [comment]
<b><i>[author="lrollus", created="ven., 20 janv. 2012 09:44:34 +0100"]</i></b>

<p> No signature of method: be.cytomine.TransactionService.stopIfTransactionInProgress() , ce sera corrigé lors du prochain deploy </p>
