### ISSUE TITLE
[CYTO-470] Metadata:No such property: text for class: java.lang.String

### ISSUE THREAD

**Issue by stevben** [cytomine/Cytomine-core-legacy#645]
<b><i>[reporter="lrollus", created="ven., 20 janv. 2012 08:07:36 +0100", resolved="ven., 20 janv. 2012 08:35:52 +0100"]</i></b>

<p>[ 10.01.12 14:00:55.277] <span class="error">&#91;http-8080-5&#93;</span><br/>
ERROR<br/>
org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver<br/>
org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver</p>

<p> Exception occurred when processing request: <span class="error">&#91;GET&#93;</span> /api/image/1465/metadata.json<br/>
Stacktrace follows:</p>

<p>groovy.lang.MissingPropertyException: No such property: text for class: java.lang.String<br/>
       at be.cytomine.api.image.RestImageController$_closure10_closure17_closure18.doCall(RestImageController.groovy:73)<br/>
       at be.cytomine.api.image.RestImageController$_closure10_closure17_closure18.doCall(RestImageController.groovy)<br/>
       at be.cytomine.api.image.RestImageController$_closure10.doCall(RestImageController.groovy:71)<br/>
       at be.cytomine.api.image.RestImageController$_closure10.doCall(RestImageController.groovy)<br/>
       at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:115)<br/>
       at java.lang.Thread.run(Thread.java:679)</p>

**Comment by stevben** [comment]
<b><i>[author="lrollus", created="ven., 20 janv. 2012 08:36:06 +0100"]</i></b>

<p>=> bug avec les upload?</p>
