### ISSUE TITLE
[CYTO-459] Problème multithreading deadlock 

### ISSUE THREAD

**Issue by stevben** [cytomine/Cytomine-core-legacy#656]
<b><i>[reporter="lrollus", created="mer., 4 janv. 2012 08:36:24 +0100", resolved="jeu., 5 janv. 2012 08:43:52 +0100"]</i></b>

<p>org.springframework.dao.DeadlockLoserDataAccessException: Hibernate operation: Could not execute JDBC batch update; SQL <span class="error">&#91;insert into image_instance (version, base_image_id, count_image_annotations, created, project_id, slide_id, updated, user_id, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?)&#93;</span>; ERROR: deadlock detected   Detail: Process 16412 waits for ExclusiveLock on tuple (0,35) of relation 952108 of database 839375; blocked by process 16430. Process 16430 waits for ShareLock on transaction 1920598; blocked by process 16412.   Hint: See server log for query details.   Where: SQL statement "UPDATE project SET count_images = count_images + 1 WHERE id =  $1 " PL/pgSQL function "incrementprojectimage" line 1 at SQL statement; nested exception is org.postgresql.util.PSQLException: ERROR: deadlock detected   Detail: Process 16412 waits for ExclusiveLock on tuple (0,35) of relation 952108 of database 839375; blocked by process 16430. Process 16430 waits for ShareLock on transaction 1920598; blocked by process 16412.   Hint: See server log for query details.   Where: SQL statement "UPDATE project SET count_images = count_images + 1 WHERE id =  $1 " PL/pgSQL function "incrementprojectimage" line 1 at SQL statement<br/>
org.springframework.dao.DeadlockLoserDataAccessException: Hibernate operation: Could not execute JDBC batch update; SQL <span class="error">&#91;insert into image_instance (version, base_image_id, count_image_annotations, created, project_id, slide_id, updated, user_id, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?)&#93;</span>; ERROR: deadlock detected<br/>
  Detail: Process 16412 waits for ExclusiveLock on tuple (0,35) of relation 952108 of database 839375; blocked by process 16430.<br/>
Process 16430 waits for ShareLock on transaction 1920598; blocked by process 16412.<br/>
  Hint: See server log for query details.<br/>
  Where: SQL statement "UPDATE project SET count_images = count_images + 1 WHERE id =  $1 "<br/>
PL/pgSQL function "incrementprojectimage" line 1 at SQL statement; nested exception is org.postgresql.util.PSQLException: ERROR: deadlock detected<br/>
  Detail: Process 16412 waits for ExclusiveLock on tuple (0,35) of relation 952108 of database 839375; blocked by process 16430.<br/>
Process 16430 waits for ShareLock on transaction 1920598; blocked by process 16412.<br/>
  Hint: See server log for query details.<br/>
  Where: SQL statement "UPDATE project SET count_images = count_images + 1 WHERE id =  $1 "<br/>
PL/pgSQL function "incrementprojectimage" line 1 at SQL statement<br/>
    at be.cytomine.test.BasicInstance.createOrGetBasicImageInstance(BasicInstance.groovy:196)<br/>
    at be.cytomine.test.BasicInstance$createOrGetBasicImageInstance.callStatic(Unknown Source)<br/>
    at be.cytomine.test.BasicInstance.createOrGetBasicAnnotation(BasicInstance.groovy:140)<br/>
    at be.cytomine.test.BasicInstance$createOrGetBasicAnnotation.call(Unknown Source)<br/>
    at be.cytomine.AnnotationAddConcurrent.<init>(MultithreadingTests.groovy:88)<br/>
    at be.cytomine.MultithreadingTests.testMultithreadAnnotationAdd(MultithreadingTests.groovy:33)<br/>
Caused by: org.postgresql.util.PSQLException: ERROR: deadlock detected<br/>
  Detail: Process 16412 waits for ExclusiveLock on tuple (0,35) of relation 952108 of database 839375; blocked by process 16430.<br/>
Process 16430 waits for ShareLock on transaction 1920598; blocked by process 16412.<br/>
  Hint: See server log for query details.<br/>
  Where: SQL statement "UPDATE project SET count_images = count_images + 1 WHERE id =  $1 "<br/>
PL/pgSQL function "incrementprojectimage" line 1 at SQL statement<br/>
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)<br/>
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)<br/>
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:407)<br/>
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2737)<br/>
    at org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)<br/>
    at org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)<br/>
    at net.bull.javamelody.JdbcWrapper.doExecute(JdbcWrapper.java:379)<br/>
    at net.bull.javamelody.JdbcWrapper$StatementInvocationHandler.invoke(JdbcWrapper.java:172)<br/>
    at net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:274)<br/>
    at $Proxy29.executeBatch(Unknown Source)<br/>
    at be.cytomine.test.BasicInstance.createOrGetBasicImageInstance(BasicInstance.groovy:196)<br/>
    at be.cytomine.test.BasicInstance$createOrGetBasicImageInstance.callStatic(Unknown Source)<br/>
    at be.cytomine.test.BasicInstance.createOrGetBasicAnnotation(BasicInstance.groovy:140)<br/>
    at be.cytomine.test.BasicInstance$createOrGetBasicAnnotation.call(Unknown Source)<br/>
    at be.cytomine.AnnotationAddConcurrent.<init>(MultithreadingTests.groovy:88)<br/>
    at be.cytomine.MultithreadingTests.testMultithreadAnnotationAdd(MultithreadingTests.groovy:33)<br/>
    at _GrailsTest_groovy$_run_closure4.doCall(_GrailsTest_groovy:271)<br/>
    at _GrailsTest_groovy$_run_closure4.call(_GrailsTest_groovy)<br/>
    at _GrailsTest_groovy$_run_closure2.doCall(_GrailsTest_groovy:228)<br/>
    at _GrailsTest_groovy$_run_closure1_closure21.doCall(_GrailsTest_groovy:187)<br/>
    at _GrailsTest_groovy$_run_closure1.doCall(_GrailsTest_groovy:174)<br/>
    at TestApp$_run_closure1.doCall(TestApp.groovy:82)<br/>
    at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)<br/>
    at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)<br/>
    at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)<br/>
    at gant.Gant.withBuildListeners(Gant.groovy:427)<br/>
    at gant.Gant.this$2$withBuildListeners(Gant.groovy)<br/>
    at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)<br/>
    at gant.Gant.dispatch(Gant.groovy:415)<br/>
    at gant.Gant.this$2$dispatch(Gant.groovy)<br/>
    at gant.Gant.invokeMethod(Gant.groovy)<br/>
    at gant.Gant.executeTargets(Gant.groovy:590)<br/>
    at gant.Gant.executeTargets(Gant.groovy:589)</p>

**Comment by stevben** [comment]
<b><i>[author="lrollus", created="jeu., 5 janv. 2012 08:43:49 +0100"]</i></b>

<p>Conflict lors de l'exécution des tests et de leur préparation. A priori ne devrait pas se produire si on passe exlusivement par des services REST</p>
